### PR TITLE
Add quit command

### PR DESCRIPTION
**Pull request by gotthardp**
https://tree.taiga.io/project/jktjkt-netconf-cli/issue/233

### CODE REVIEW

**Comment by jktjkt** [comment]
Hi there, can you please submit this via Gerrit? Here are the [instructions](https://gerrit-review.googlesource.com/Documentation/user-upload.html). When signing in, choose "*CESNET - Sign in with GitHub*" and you won't need any extra account.

**Comment by jktjkt** [comment]
Actually, [this link](https://gerrit-review.googlesource.com/Documentation/intro-user.html) is better, sorry :).

**Comment by syyyr** [comment]
Hi. I looked at the code and I think there are no issues. Thanks!

**Comment by gotthardp** [comment]
Oh, thanks. I missed that login option. Sorry for that.

**Pull request closed without merging**
